version: "3"
services:
  jenkins:
    # image: jenkins/jenkins
    build: .
    container_name: jenkins-container
    ports: 
      - "8090:8080"
    volumes:
      - ./jenkins-home:/var/jenkins_home
    networks: 
      - ssh_net  
networks: 
  ssh_net:

